# Generated by Django 5.0.7 on 2024-07-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_dated',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(default='0794499939'),
        ),
    ]
